name: dbus-client
version: '0.1'
summary: D-Bus client example
description: |
  This is a simple D-Bus client application written in C.
base: core22
grade: stable
confinement: classic

apps:
  client:
    command: bin/client
    plugs: [dbus-client]

parts:
  client:
    plugin: make
    source: .
    build-packages:
      - libdbus-1-dev
    stage-packages:
      - libdbus-1-3
      #- client  # Add this line
    override-build: |
      make
      echo "Current directory: $(pwd)"
      echo "Contents of current directory:"
      ls -l
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp client $SNAPCRAFT_PART_INSTALL/bin/
      echo "Contents of $SNAPCRAFT_PART_INSTALL/bin/:"
      ls -l $SNAPCRAFT_PART_INSTALL/bin/
      chmod 755 $SNAPCRAFT_PART_INSTALL/bin/client
    #  install -D client $SNAPCRAFT_STAGE/bin/client  # Add this line

plugs:
  dbus-client:
    interface: dbus
    bus: session
    name: test.method.server

