name: bacnet-stack
version: '0.1'
summary: A sample snap pacakage which has 2 processes
description: |
  This is a sample snap for demonstration purposes.
base: core22
grade: stable
confinement: classic
architectures:
  - build-on: amd64
parts:
  process1:
    source: https://github.com/samarthsortur/snap-demo.git
    source-type: git
    source-branch: main
    plugin: make
    override-build: |
      cd process1
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp process1 $SNAPCRAFT_PART_INSTALL/bin/
      chmod 755 $SNAPCRAFT_PART_INSTALL/bin/process1
apps:
  process1:
    command: bin/process1