name: dbus-server
version: '0.1'
summary: D-Bus server example
description: |
  This is a simple D-Bus server application written in C.

grade: stable
confinement: classic
base: core22
apps:
  server:
    command: bin/server
    slots: [dbus-server]
    
parts:
  client:
    plugin: make
    source: .
    build-packages:
      - libdbus-1-dev
    stage-packages:
      - libdbus-1-3
      #- client  # Add this line
    override-build: |
      make
      echo "Current directory: $(pwd)"
      echo "Contents of current directory:"
      ls -l
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp server $SNAPCRAFT_PART_INSTALL/bin/
      echo "Contents of $SNAPCRAFT_PART_INSTALL/bin/:"
      ls -l $SNAPCRAFT_PART_INSTALL/bin/
      chmod 755 $SNAPCRAFT_PART_INSTALL/bin/server
    #  install -D client $SNAPCRAFT_STAGE/bin/client  # Add this line

slots:
  dbus-server:
    interface: dbus
    bus: session
    name: test.method.server

